[build]
  # folder in which netlify should look for package.json, site content, etc.
  base = "/"

  # folder with assets that should be hosted by netlify, i.e. the build output, relative to base
  publish = "public/"

  # the command to build the site
  command = "npm run build"

[functions]
  # folder that contains netlify functions, relative to base
  directory = "functions/"

[[redirects]]
  from = "/*"
  to = "https://linktr.ee/brunoroemers"